### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CyberL1** [MPLauncher/MPLauncher#11]
How to add mods by files (not by the launcher)

**Comment by tboba** [comment]
@CyberLinx Hi, sorry for the late answer.

We're sorry, but our launcher is still in the work state. While we are still working on the launcher design, you can't play minecraft on the second version of our launcher, sorry.

If you want to play on MPLauncher - you can launch the older, v1 version. You can download it from the website attached in the README.md from our repository.
In v1 version you can create your own pack in the launcher, and add mods through the mods folder in the instances folder.

Best regards,
MP Launcher Team
