### ISSUE TITLE
Błąd uruchamiania Launchera

### ISSUE THREAD

**Issue by Adrien-234** [MPLauncher/MPLauncher#13]
Kiedy uruchamiam launcher pojawia się komunikat że nie ma dostępu do internetu. Pobrałem najnowszą wersję MP i wersję XP ale problem nadal występuje . Mam najnowszą wersję Win 10. Teraz nie mogę wogóle uruchomić MC. Proszę o pomoc.

![image](https://user-images.githubusercontent.com/80624860/113201929-6b573c80-926a-11eb-8eee-386659862aa8.png)

**Comment by LosTigeros** [comment]
Proszę pobrać najnowszą wersję launchera, nie dla systemów XP.

**Comment by Adrien-234** [comment]
Znalazłem problem.
Launcher mam w .mplauncher i niestety nie działa ale kiedy przeniosę gdzieś indziej to zaczyna działać (ma internet)
